version: '2'

services:
  php: 
    build: ./php
    volumes:
      - ./src:/var/www
  
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    platform: linux/x86_64 # M1Mac対応
    ports:
      - "33306:80"
    environment:
      MYSQL_ROOT_PASSWORD: testdb 